# Generated by Django 5.0.7 on 2026-04-27 03:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_historicalentity_historicalfarm_historicaljobrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('adjustment_type', models.CharField(choices=[('absence', 'Falta'), ('advance', 'Adiantamento'), ('other_discount', 'Outro desconto'), ('other_credit', 'Outro crédito')], max_length=20, verbose_name='Tipo')),
                ('reference_year', models.PositiveSmallIntegerField(verbose_name='Ano de referência')),
                ('reference_month', models.PositiveSmallIntegerField(verbose_name='Mês de referência')),
                ('event_date', models.DateField(verbose_name='Data do evento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('system', 'Sistema'), ('advance_module', 'Módulo de adiantamentos')], default='manual', max_length=20, verbose_name='Origem')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.person', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'historical Ajuste',
                'verbose_name_plural': 'historical Ajustes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('adjustment_type', models.CharField(choices=[('absence', 'Falta'), ('advance', 'Adiantamento'), ('other_discount', 'Outro desconto'), ('other_credit', 'Outro crédito')], max_length=20, verbose_name='Tipo')),
                ('reference_year', models.PositiveSmallIntegerField(verbose_name='Ano de referência')),
                ('reference_month', models.PositiveSmallIntegerField(verbose_name='Mês de referência')),
                ('event_date', models.DateField(verbose_name='Data do evento')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('system', 'Sistema'), ('advance_module', 'Módulo de adiantamentos')], default='manual', max_length=20, verbose_name='Origem')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='employees.person', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
                'ordering': ['-reference_year', '-reference_month', 'person__name'],
                'indexes': [models.Index(fields=['person', 'reference_year', 'reference_month'], name='attendance__person__e4d841_idx')],
            },
        ),
    ]
