# Generated by Django 5.0.7 on 2026-04-29 04:40

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0002_historicalentity_historicalfarm_historicaljobrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDiscountInstallment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('installment_type', models.CharField(choices=[('advance', 'Adiantamento'), ('loan', 'Empréstimo'), ('other', 'Outro desconto parcelado')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('num_installments', models.PositiveSmallIntegerField(verbose_name='Número de parcelas')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por parcela')),
                ('first_reference_year', models.PositiveSmallIntegerField(verbose_name='Ano inicial')),
                ('first_reference_month', models.PositiveSmallIntegerField(verbose_name='Mês inicial')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Desconto parcelado',
                'verbose_name_plural': 'historical Descontos parcelados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número da parcela'),
        ),
        migrations.AddField(
            model_name='historicaladjustment',
            name='installment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número da parcela'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('absence', 'Falta'), ('advance', 'Adiantamento'), ('installment', 'Parcela de desconto'), ('fine', 'Multa'), ('transport', 'Vale transporte'), ('health', 'Plano de saúde'), ('other_discount', 'Outro desconto'), ('overtime', 'Hora extra'), ('bonus', 'Bônus / Gratificação'), ('other_credit', 'Outro crédito')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'Sistema'), ('installment_module', 'Módulo de parcelamento'), ('advance_module', 'Módulo de adiantamentos')], default='manual', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='adjustment',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Negativo para desconto, positivo para crédito.', max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='historicaladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('absence', 'Falta'), ('advance', 'Adiantamento'), ('installment', 'Parcela de desconto'), ('fine', 'Multa'), ('transport', 'Vale transporte'), ('health', 'Plano de saúde'), ('other_discount', 'Outro desconto'), ('overtime', 'Hora extra'), ('bonus', 'Bônus / Gratificação'), ('other_credit', 'Outro crédito')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicaladjustment',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('system', 'Sistema'), ('installment_module', 'Módulo de parcelamento'), ('advance_module', 'Módulo de adiantamentos')], default='manual', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='historicaladjustment',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Negativo para desconto, positivo para crédito.', max_digits=10, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='DiscountInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('installment_type', models.CharField(choices=[('advance', 'Adiantamento'), ('loan', 'Empréstimo'), ('other', 'Outro desconto parcelado')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('num_installments', models.PositiveSmallIntegerField(verbose_name='Número de parcelas')),
                ('installment_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por parcela')),
                ('first_reference_year', models.PositiveSmallIntegerField(verbose_name='Ano inicial')),
                ('first_reference_month', models.PositiveSmallIntegerField(verbose_name='Mês inicial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installments_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='employees.person', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Desconto parcelado',
                'verbose_name_plural': 'Descontos parcelados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='adjustment',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='attendance.discountinstallment', verbose_name='Parcelamento origem'),
        ),
        migrations.AddField(
            model_name='historicaladjustment',
            name='installment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.discountinstallment', verbose_name='Parcelamento origem'),
        ),
        migrations.AddIndex(
            model_name='adjustment',
            index=models.Index(fields=['adjustment_type', 'reference_year', 'reference_month'], name='attendance__adjustm_8ce943_idx'),
        ),
        migrations.AddField(
            model_name='historicaldiscountinstallment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicaldiscountinstallment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldiscountinstallment',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.person', verbose_name='Colaborador'),
        ),
    ]
