# Generated by Django 5.0.7 on 2026-04-27 03:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0002_historicalentity_historicalfarm_historicaljobrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('requested_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor solicitado')),
                ('approved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aprovado')),
                ('request_date', models.DateField(verbose_name='Data da solicitação')),
                ('discount_reference_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de desconto')),
                ('discount_reference_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês de desconto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('discounted', 'Descontado')], default='pending', max_length=15, verbose_name='Status')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rejeição')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('generated_adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance', to='attendance.adjustment', verbose_name='Ajuste gerado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='employees.person', verbose_name='Colaborador')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances_requested', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advances_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
            ],
            options={
                'verbose_name': 'Adiantamento',
                'verbose_name_plural': 'Adiantamentos',
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAdvance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Excluído')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Excluído em')),
                ('requested_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor solicitado')),
                ('approved_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor aprovado')),
                ('request_date', models.DateField(verbose_name='Data da solicitação')),
                ('discount_reference_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de desconto')),
                ('discount_reference_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês de desconto')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('discounted', 'Descontado')], default='pending', max_length=15, verbose_name='Status')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo de rejeição')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('generated_adjustment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='attendance.adjustment', verbose_name='Ajuste gerado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.person', verbose_name='Colaborador')),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
            ],
            options={
                'verbose_name': 'historical Adiantamento',
                'verbose_name_plural': 'historical Adiantamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
